### ISSUE TITLE
exception errors 

### ISSUE THREAD

**Issue by mhwlng** [episerver/EPiServer.Labs.BlockEnhancements#22]
We've installed this nuget package and now we are getting regular exceptions:

`https://................/cms/Stores/contentversion/?contentLink=14876&query=getcommondraftversion&dojo.preventCache=1569486912105 `

```
Object reference not set to an instance of an object.
   at EPiServer.Cms.Shell.UI.Rest.Internal.ContentVersionStore.CheckAccessLevel(ContentVersion version, AccessLevel[] accessLevels)
   at EPiServer.Cms.Shell.UI.Rest.Internal.ContentVersionStore.GetCommonDraftVersion(ContentReference contentLink, String language)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at EPiServer.Shell.Services.Rest.RestControllerBase.EndExecute(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by barteksekula** [comment]
@mhwlng when does this exception happen? Do you have to run any specific action or it just breaks the whole site after install?

**Comment by mhwlng** [comment]
I'm afraid I don't know. 
Our CMS people are using it since today and I saw about 10 of these errors in the logs within an hour for different blocks and different people. 
At the moment I'm not seeing any errors anymore for several hours.
It doesn't seem to bring down the CMS? And 
the content editors didn't report any failures during their workflow.
(note that Our CMS is on a different server from the websites)

**Comment by mhwlng** [comment]
I'm seeing another 6 or so of these errors in 10 minutes
If I request the relevant link that causes the exception manually

`https://habufacms.hendersandhazel.com:8081/HabufaCMS/cms/Stores/contentversion/?contentLink=14879&query=getcommondraftversion&dojo.preventCache=1569500690091`

I get some JSON

`{}&&[{"isCommonDraft":true,"allowToDelete":false,"contentLink":"14879_40720","language":"nl-BE","name":"15 jaar A & B","savedBy":"p.m","statusChangedBy":"p.m","savedDate":"2019-09-26T12:26:30Z","uri":"epi.cms.contentdata:///14879_40720","status":4,"typeIdentifier":"epiwebsite.models.blocks.mediablock"},{"isCommonDraft":false,"allowToDelete":true,"contentLink":"14879_40719","language":"nl-BE","name":"15 jaar A & B ","savedBy":"p.m","statusChangedBy":"p.m","savedDate":"2019-09-26T12:25:47Z","uri":"epi.cms.contentdata:///14879_40719","status":5,"typeIdentifier":"epiwebsite.models.blocks.mediablock"},{"isCommonDraft":true,"allowToDelete":false,"contentLink":"14879_40388","language":"nl","name":"15 jaar A & B","savedBy":"p.m","statusChangedBy":"p.m","savedDate":"2019-09-24T12:34:47Z","uri":"epi.cms.contentdata:///14879_40388","status":4,"typeIdentifier":"epiwebsite.models.blocks.mediablock"}]`

**Comment by barteksekula** [comment]
@mhwlng I'm not sure what can I do, tried to reproduce this but with no luck. would it be possible for you to somehow sync with the editors and provide some kind of steps to reproduce?

**Comment by mhwlng** [comment]
Thanks for looking into it. 
Unfortunately, I also can't reproduce  the problem and I have not been able to pinpoint the problem to certain operations, that the editors do.
The editors don't see any problems with the content and they also don't see any error messages.
